import fs from 'node:fs';

const sourcePath = 'c:/Users/sahma/Desktop/Slides E2T Affiliate EN/assets/index-UFoGpxLQ.js';
const targetPath = 'c:/Users/sahma/Desktop/Slides E2T Affiliate EN/assets/index-UFoGpxLQ.fix.js';

let content = fs.readFileSync(sourcePath, 'utf8');

const replacements = [
  ['// Affiliate Guide', '// Guia de Afiliados'],
  ['Affiliate Guide', 'Guia de Afiliados'],
  ['Offers, rules, and commissions for affiliates.', 'Ofertas, regras e comissoes para afiliados.'],
  ['Cover slide - Offers, rules, and commissions for affiliates.', 'Slide de capa - Ofertas, regras e comissoes para afiliados.'],
  ['Overview - Two main offers', 'Visao geral - Duas ofertas principais'],
  ['// 02 — Overview', '// 02 — Visao geral'],
  ['// 18 — Next steps', '// 18 — Proximos passos'],
  ['Two offers,', 'Duas ofertas,'],
  ['two trader profiles.', 'dois perfis de trader.'],
  ['Offer 01', 'Oferta 01'],
  ['Offer 02', 'Oferta 02'],
  ['Trader Career Path', 'Percurso de Carreira do Trader'],
  ['Subscricao exam', 'Prova por subscricao'],
  ['Progressive, long-term scaling path from evaluation to funded accounts.', 'Percurso progressivo e de longo prazo desde a avaliacao ate contas financiadas.'],
  ['Progressive, long-term scaling path from 25K to 400K. For traders who want structure and time.', 'Percurso progressivo e de longo prazo de 25K ate 400K. Para traders que procuram estrutura e tempo.'],
  ['Progressive, long-term scaling path from ', 'Percurso progressivo e de longo prazo de '],
  [' to ', ' ate '],
  ['. For traders who want structure and time.', '. Para traders que procuram estrutura e tempo.'],
  ['Exam-style challenge with fixed metrics and a direct route to a funded offer.', 'Desafio em formato de prova com metricas fixas e acesso direto a uma oferta financiada.'],
  ['Intraday evaluation on a subscription. For traders with a ready strategy who want a focused exam.', 'Avaliacao intradiaria por subscricao. Para traders com uma estrategia pronta que querem uma prova focada.'],
  ['TCP vs Gauntlet Mini at a glance.', 'TCP vs Gauntlet Mini num relance.'],
  ['TCP - What it is', 'TCP - O que e'],
  ['TCP — What it is', 'TCP — O que e'],
  ['TCP — Evaluation rules', 'TCP — Regras de avaliacao'],
  ['TCP — Funding, scaling and fees', 'TCP — Financiamento, escalonamento e taxas'],
  ['TCP - Evaluation rules', 'TCP - Regras de avaliacao'],
  ['TCP - Funding, scaling and fees', 'TCP - Financiamento, escalonamento e taxas'],
  ['Gauntlet Mini - What it is', 'Gauntlet Mini - O que e'],
  ['Gauntlet Mini — What it is', 'Gauntlet Mini — O que e'],
  ['Gauntlet Mini — Rules', 'Gauntlet Mini — Regras'],
  ['Gauntlet Mini — Pricing & account sizes', 'Gauntlet Mini — Precos e tamanhos de conta'],
  ['Gauntlet Mini — Funding & progression', 'Gauntlet Mini — Financiamento e progressao'],
  ['Gauntlet Mini - Rules', 'Gauntlet Mini - Regras'],
  ['Gauntlet Mini - Pricing & account sizes', 'Gauntlet Mini - Precos e tamanhos de conta'],
  ['Gauntlet Mini - Funding & progression', 'Gauntlet Mini - Financiamento e progressao'],
  ['Affiliate program - Commissions & payouts', 'Programa de afiliados - Comissoes e pagamentos'],
  ['Affiliate program - Active status & rules', 'Programa de afiliados - Estado ativo e regras'],
  ['Affiliate program — Commissions & payouts', 'Programa de afiliados — Comissoes e pagamentos'],
  ['Affiliate program — Active status & rules', 'Programa de afiliados — Estado ativo e regras'],
  ['Progression ladder & contracts', 'Escada de progressao e contratos'],
  ['Drawdown types', 'Tipos de drawdown'],
  ['Objectives & consistency', 'Objetivos e consistencia'],
  ['Tradable assets & restrictions', 'Ativos negociaveis e restricoes'],
  ['Account types & data fees', 'Tipos de conta e taxas de dados'],
  ['Which offer to recommend', 'Que oferta recomendar'],
  ['Next steps for affiliates', 'Proximos passos para afiliados'],
  ['first 2y', 'primeiros 2a'],
  ['lifetime', 'vitalicio'],

  ['// 03 \u2014 Offer 01 \u00b7 TCP', '// 03 \u2014 Oferta 01 \u00b7 TCP'],
  ['Progressive futures funding with three starting tiers.', 'Financiamento progressivo de futuros com tres niveis iniciais.'],
  ['TIER 01', 'NIVEL 01'],
  ['TIER 02', 'NIVEL 02'],
  ['TIER 03', 'NIVEL 03'],
  ['25K start \u00b7 scales to 200K', 'Inicio em 25K \u00b7 escala ate 200K'],
  ['50K start \u00b7 scales to 400K', 'Inicio em 50K \u00b7 escala ate 400K'],
  ['100K start \u00b7 scales to 400K', 'Inicio em 100K \u00b7 escala ate 400K'],
  ['Trader passes a simulated evaluation, then upgrades through LiveSim or Live funded accounts with an 80/20 profit split. Custom funding offer at the top tier.', 'O trader passa uma avaliacao simulada e depois evolui por LiveSim ou contas reais financiadas com divisao de lucro 80/20. Oferta de financiamento personalizada no nivel mais alto.'],
  ['Traders who want structured, long-term scaling and can follow the rules.', 'Traders que procuram um escalonamento estruturado e de longo prazo e conseguem seguir as regras.'],

  ['// 04 \u2014 TCP \u00b7 Evaluation rules', '// 04 \u2014 TCP \u00b7 Regras de avaliacao'],
  ['What it takes to pass.', 'O que e preciso para passar.'],
  ['01 \u00b7 MIN DAYS', '01 \u00b7 DIAS MINIMOS'],
  ['At least 10 trading days.', 'Pelo menos 10 dias de negociacao.'],
  ['02 \u00b7 DAILY LOSS', '02 \u00b7 PERDA DIARIA'],
  ['Daily loss limit \u2014 never reach or drop below. Open and closed equity count.', 'Limite de perda diaria \u2014 nunca atingir nem descer abaixo. O capital aberto e fechado conta.'],
  ['03 \u00b7 PROGRESSION LADDER', '03 \u00b7 ESCADA DE PROGRESSAO'],
  ['Progression Ladder', 'Escada de Progressao'],
  ['Progression Ladder \u2014 do not exceed allowed contracts for your balance.', 'Escada de Progressao \u2014 nao exceder os contratos permitidos para o seu saldo.'],
  ['04 \u00b7 EOD DRAWDOWN', '04 \u00b7 DRAWDOWN EOD'],
  ['EOD drawdown', 'Drawdown EOD'],
  ['EOD drawdown \u2014 never reach or drop below the minimum balance.', 'Drawdown EOD \u2014 nunca atingir nem descer abaixo do saldo minimo.'],
  ['05 \u00b7 APPROVED TIMES', '05 \u00b7 HORARIOS APROVADOS'],
  ['Trade only during authorized exchange hours.', 'Negociar apenas durante os horarios autorizados da bolsa.'],
  ['06 \u00b7 CONSISTENCY', '06 \u00b7 CONSISTENCIA'],
  ['Consistency rule', 'Regra de consistencia'],
  ['Consistency rule \u2014 best day under 30% of total profit.', 'Regra de consistencia \u2014 melhor dia abaixo de 30% do lucro total.'],
  ['Rule break \u2192 hard risk-rule breaches fail the evaluation. Progression Ladder overages can lock trading for the day.', 'Quebra de regra \u2192 violacoes graves de risco reprovam a avaliacao. Exceder a Escada de Progressao pode bloquear a negociacao no dia.'],

  ['// 05 \u2014 TCP \u00b7 Funding, scaling, fees', '// 05 \u2014 TCP \u00b7 Financiamento, escalonamento e taxas'],
  ['How traders get paid.', 'Como os traders sao pagos.'],
  ['FUNDING OFFER', 'OFERTA DE FINANCIAMENTO'],
  ['Guaranteed funded offer from partner firms matching the TCP tier completed.', 'Oferta de financiamento garantida de empresas parceiras, correspondente ao nivel TCP concluido.'],
  ['PROFIT SPLIT', 'DIVISAO DE LUCROS'],
  ["In trader's favor.", 'A favor do trader.'],
  ['ACTIVATION FEE', 'TAXA DE ATIVACAO'],
  ['One-time, non-pros. Deducted from first withdrawal.', 'Pagamento unico para nao profissionais. Deduzido no primeiro levantamento.'],
  ['Scaling tiers', 'Niveis de escalonamento'],
  ['\u2192 up to 200K', '\u2192 ate 200K'],
  ['\u2192 up to 400K', '\u2192 ate 400K'],
  ['Drawdown by phase', 'Drawdown por fase'],
  ['Evaluation \u00b7 LiveSim', 'Avaliacao \u00b7 LiveSim'],
  ['Largest funded tier', 'Maior nivel financiado'],
  ['Fixed', 'Fixo'],
  ['"Progression: hitting profit target and withdrawing triggers auto-upgrade to the next tier."', '"Progressao: atingir a meta de lucro e levantar fundos ativa a subida automatica para o nivel seguinte."'],

  ['// 06 \u2014 Offer 02 \u00b7 Gauntlet Mini', '// 06 \u2014 Oferta 02 \u00b7 Gauntlet Mini'],
  ['Intraday futures trading exam on a subscription.', 'Prova intradiaria de negociacao de futuros por subscricao.'],
  ['Subscription-based intraday exam. Trader keeps trading until they pass, cancel, or reset.', 'Prova intradiaria baseada em subscricao. O trader continua a negociar ate passar, cancelar ou reiniciar.'],
  ['Outcome', 'Resultado'],
  ['Passing with rules respected leads to a guaranteed funded offer from Helios Trading Partners, aligned with the evaluation account parameters.', 'Passar com as regras cumpridas leva a uma oferta financiada garantida da Helios Trading Partners, alinhada com os parametros da conta de avaliacao.'],
  ['Ideal client', 'Cliente ideal'],
  ['Traders with a ready strategy who want a focused exam instead of a long progression path.', 'Traders com estrategia pronta que querem uma prova focada em vez de um percurso longo de progressao.'],

  ['// 07 \u2014 Gauntlet Mini \u00b7 Rules', '// 07 \u2014 Gauntlet Mini \u00b7 Regras'],
  ['The exam rules.', 'As regras da prova.'],
  ['02 \u00b7 MARKET HOURS', '02 \u00b7 HORARIOS DE MERCADO'],
  ['Trade only in approved exchange hours.', 'Negociar apenas nos horarios aprovados da bolsa.'],
  ['03 \u00b7 DAILY LOSS \u00b7 HARD', '03 \u00b7 PERDA DIARIA \u00b7 GRAVE'],
  ['Daily loss limit \u2014 hitting it fails the evaluation.', 'Limite de perda diaria \u2014 ao atingir, reprova a avaliacao.'],
  ['04 \u00b7 EOD DRAWDOWN \u00b7 HARD', '04 \u00b7 DRAWDOWN EOD \u00b7 GRAVE'],
  ['EOD drawdown \u2014 hitting the minimum balance is a hard breach.', 'Drawdown EOD \u2014 atingir o saldo minimo e uma violacao grave.'],
  ['05 \u00b7 LADDER \u00b7 SOFT', '05 \u00b7 ESCADA \u00b7 LEVE'],
  ['Progression Ladder \u2014 exceeding contract limits blocks the account until next trading day.', 'Escada de Progressao \u2014 exceder os limites de contratos bloqueia a conta ate ao dia seguinte de negociacao.'],
  ['Consistency rule \u2014 best day under 30% of total profit; if over 30%, the drawdown floor can keep climbing until it reaches starting balance.', 'Regra de consistencia \u2014 melhor dia abaixo de 30% do lucro total; se passar 30%, o limite de drawdown pode continuar a subir ate atingir o saldo inicial.'],
  ['07 \u00b7 COPYTRADING', '07 \u00b7 COPYTRADING'],
  ['Forbidden.', 'Proibido.'],
  ['Hard breach \u2192', 'Violacao grave \u2192'],
  ['Hard breach ->', 'Violacao grave ->'],
  ['fails the evaluation. Reset required.', 'reprova a avaliacao. Reinicio obrigatorio.'],

  ['// 08 \u2014 Gauntlet Mini \u00b7 Pricing & account sizes', '// 08 \u2014 Gauntlet Mini \u00b7 Precos e tamanhos de conta'],
  ['Pick the size, know the math.', 'Escolha o tamanho, conheca os numeros.'],
  ['Size', 'Tamanho'],
  ['Subscription', 'Subscricao'],
  ['Reset fee', 'Taxa de reinicio'],
  ['Profit target', 'Meta de lucro'],
  ['Daily loss \u00b7 Max DD', 'Perda diaria \u00b7 DD max'],
  ['Contracts', 'Contratos'],
  ['dynamic (promo)', 'dinamica (promo)'],
  ['Subscription \u2014 renewals do not reset balance.', 'Subscricao \u2014 renovacoes nao reiniciam o saldo.'],
  ['Resets \u2014 available anytime in evaluation, do not extend subscription, not available once funded.', 'Reinicios \u2014 disponiveis a qualquer momento na avaliacao, nao prolongam a subscricao e nao estao disponiveis apos financiamento.'],

  ['// 09 \u2014 Gauntlet Mini \u00b7 Funding & progression', '// 09 \u2014 Gauntlet Mini \u00b7 Financiamento e progressao'],
  ['The path from pass to live capital.', 'O percurso da aprovacao ao capital real.'],
  ['STAGE 01 \u00b7 LIVESIM', 'FASE 01 \u00b7 LIVESIM'],
  ['Quick setup, withdrawals on.', 'Configuracao rapida, levantamentos ativos.'],
  ['Allows withdrawals', 'Permite levantamentos'],
  ['Transitions to Live after first $5K profit (minus 20% split)', 'Passa para Real apos os primeiros $5K de lucro (menos 20% de divisao)'],
  ['STAGE 02 \u00b7 LIVE', 'FASE 02 \u00b7 REAL'],
  ['Real brokerage account.', 'Conta real de corretora.'],
  ['Pass-through CME data fees (~$140\u2013156 / exchange / month)', 'Taxas CME de dados repercutidas (~$140\u2013156 / bolsa / mes)'],
  ['5 days of unscheduled inactivity can terminate the account', '5 dias de inatividade nao programada podem terminar a conta'],
  ['FUNDED BY', 'FINANCIADO POR'],
  ['$139 non-pros', '$139 nao profissionais'],

  ['// 10 \u2014 Affiliate program \u00b7 Commissions', '// 10 \u2014 Programa de afiliados \u00b7 Comissoes'],
  ['CPS recurring. Paid monthly.', 'CPS recorrente. Pago mensalmente.'],
  ['YEAR 1 \u2014 2', 'ANO 1 \u2014 2'],
  ['YEAR 1 - 2', 'ANO 1 - 2'],
  ['On all payments from a new client for the first 2 years.', 'Em todos os pagamentos de um novo cliente durante os primeiros 2 anos.'],
  ['YEAR 3 +', 'ANO 3 +'],
  ['Lifetime on payments after 2 years, while affiliate remains active.', 'Vitalicio nos pagamentos apos 2 anos, enquanto o afiliado se mantiver ativo.'],
  ['PAYOUTS', 'PAGAMENTOS'],
  ['Monthly, between the 5th and 10th', 'Mensalmente, entre os dias 5 e 10'],
  ['MIN PAYOUT', 'PAGAMENTO MINIMO'],
  ['$300 standard', '$300 padrao'],
  ['EARLY WITHDRAW', 'LEVANTAMENTO ANTECIPADO'],
  ['Under $300 allowed \u00b7 30% fee', 'Abaixo de $300 permitido \u00b7 30% taxa'],
  ['METHODS', 'METODOS'],
  ['Self-purchase \u2192 commissions can be used to buy accounts or resets with a 20% extra discount on top of current promotions.', 'Auto-compra \u2192 as comissoes podem ser usadas para comprar contas ou reinicios com um desconto extra de 20% sobre as promocoes atuais.'],

  ['// 11 \u2014 Affiliate program \u00b7 Active status & rules', '// 11 \u2014 Programa de afiliados \u00b7 Estado ativo e regras'],
  ['Stay active, keep the tier.', 'Mantenha-se ativo, mantenha o nivel.'],
  ['Active affiliate requirement', 'Requisito de afiliado ativo'],
  ['Maintain active status under the current affiliate terms to keep your payout tier. Confirm current requirements in the affiliate portal before promoting.', 'Mantenha o estado ativo segundo os termos atuais de afiliado para manter o seu nivel de pagamento. Confirme os requisitos atuais no portal de afiliados antes de promover.'],
  ['All sales tracked via affiliate links and the affiliate portal.', 'Todas as vendas sao rastreadas por links de afiliado e pelo portal de afiliados.'],
  ['Tools provided', 'Ferramentas disponibilizadas'],
  ['Referral links', 'Links de referencia'],
  ['Personal discount codes', 'Codigos de desconto pessoais'],
  ['Banners and emails', 'Banners e emails'],
  ['Landing pages in multiple languages', 'Paginas de destino em varios idiomas'],
  ['Brand & compliance', 'Marca e conformidade'],
  ['No misleading promises \u2014 for example, "no rules" or "no data fees ever."', 'Sem promessas enganosas \u2014 por exemplo, "sem regras" ou "sem taxas de dados para sempre".'],
  ['Respect Earn2Trade brand guidelines and disclaimers.', 'Respeite as diretrizes de marca e os avisos legais da Earn2Trade.'],

  ['// 12 \u2014 General rules \u00b7 Progression ladder', '// 12 \u2014 Regras gerais \u00b7 Escada de progressao'],
  ['More balance, more contracts.', 'Mais saldo, mais contratos.'],
  ['The Progression Ladder caps the max contracts per balance. A higher balance allows more contracts.', 'A Escada de Progressao limita os contratos maximos por saldo. Um saldo mais alto permite mais contratos.'],
  ['Violation', 'Violacao'],
  ['Opening more contracts than allowed blocks the account for the day (soft breach). Combined with other rule breaks, it can fail the evaluation.', 'Abrir mais contratos do que o permitido bloqueia a conta no dia (violacao leve). Combinada com outras quebras de regra, pode reprovar a avaliacao.'],
  ['Affiliate message', 'Mensagem para afiliados'],
  ['"Don\'t oversize. Follow the contract ladder."', '"Nao sobrealavanque. Siga a escada de contratos."'],

  ['// 13 \u2014 General rules \u00b7 Drawdown types', '// 13 \u2014 Regras gerais \u00b7 Tipos de drawdown'],
  ['Three drawdowns, three phases.', 'Tres drawdowns, tres fases.'],
  ['TYPE 01', 'TIPO 01'],
  ['Evaluations \u00b7 LiveSim', 'Avaliacoes \u00b7 LiveSim'],
  ['Minimum balance updates at day end when hitting new highs. Stops rising at the starting balance.', 'O saldo minimo atualiza no fim do dia ao atingir novos maximos. Deixa de subir no saldo inicial.'],
  ['TYPE 02', 'TIPO 02'],
  ['Trailing drawdown', 'Drawdown trailing'],
  ['Live funded accounts', 'Contas reais financiadas'],
  ['Updates continuously intraday as new highs are reached.', 'Atualiza continuamente intradiario quando sao atingidos novos maximos.'],
  ['TYPE 03', 'TIPO 03'],
  ['Fixed drawdown', 'Drawdown fixo'],
  ['Largest funded TCP tier', 'Maior nivel TCP financiado'],
  ['Fixed at $194K on 200K, and $388K on 400K accounts.', 'Fixo em $194K nas contas de 200K e em $388K nas contas de 400K.'],
  ['Important \u2014 open equity can still fail an account even with EOD drawdown if it dips under the minimum.', 'Importante \u2014 o capital aberto ainda pode reprovar uma conta mesmo com drawdown EOD se cair abaixo do minimo.'],

  ['// 14 \u2014 General objectives & consistency', '// 14 \u2014 Objetivos gerais e consistencia'],
  ['The non-negotiables.', 'Os inegociaveis.'],
  ['10 trading days', '10 dias de negociacao'],
  ['Minimum across all evaluations.', 'Minimo em todas as avaliacoes.'],
  ['Approved hours only', 'Apenas horarios aprovados'],
  ['CME, CBOT, NYMEX, COMEX hours.', 'Horarios CME, CBOT, NYMEX e COMEX.'],
  ['Hard risk rules', 'Regras de risco graves'],
  ['Daily loss limit and EOD drawdown \u2014 breaking them fails the evaluation.', 'Limite de perda diaria e drawdown EOD \u2014 quebrar estas regras reprova a avaliacao.'],
  ['Consistency rule \u00b7 30%', 'Regra de consistencia \u00b7 30%'],
  ['Best day under 30% of total profit target. Stops "one lucky day" passes.', 'Melhor dia abaixo de 30% da meta de lucro total. Evita aprovacoes por "um dia de sorte".'],
  ['Trader must reach the profit target for their account size and meet all other objectives.', 'O trader deve atingir a meta de lucro para o tamanho da sua conta e cumprir todos os outros objetivos.'],

  ['Trade these. Skip those.', 'Negocie estes. Evite os restantes.'],
  ['NOT ALLOWED', 'NAO PERMITIDO'],
  ['ALLOWED', 'PERMITIDO'],
  ['All CME futures', 'Todos os futuros CME'],
  ['Forex & crypto futures', 'Forex e futuros de cripto'],
  ['Bitcoin futures are not allowed on live accounts and do not count toward completion. Ether futures are not allowed.', 'Futuros de Bitcoin nao sao permitidos em contas reais e nao contam para conclusao. Futuros de Ether nao sao permitidos.'],
  ['Liquidity warning', 'Aviso de liquidez'],
  ['Low-liquidity contracts can cause large swings in open equity. Any fails from this remain the trader\'s responsibility.', 'Contratos de baixa liquidez podem causar grandes oscilacoes no capital aberto. Qualquer reprovao por este motivo e da responsabilidade do trader.'],

  ['The three account states.', 'Os tres estados de conta.'],
  ['EVALUATION', 'AVALIACAO'],
  ['Simulated', 'Simulada'],
  ['Real-time', 'Tempo real'],
  ['Monthly sub', 'Subscricao mensal'],
  ['LIVESIM', 'LIVESIM'],
  ['Simulated, withdrawable', 'Simulada, com levantamentos'],
  ['$139 once (non-pro)', '$139 uma vez (nao profissional)'],
  ['10-day rule', 'Regra dos 10 dias'],
  ['CME data', 'Dados CME'],
  ['All pros & non-pros', 'Todos os profissionais e nao profissionais'],
  ['Evaluations \u2192 non-pros pay no extra data fees. Pros pay per exchange each month.', 'Avaliacoes \u2192 os nao profissionais nao pagam taxas extra de dados. Os profissionais pagam por bolsa todos os meses.'],

  ['Match the trader to the offer.', 'Associe o trader a oferta certa.'],
  ['RECOMMEND TCP WHEN', 'RECOMENDAR TCP QUANDO'],
  ['Trader wants long-term, staged growth up to ', 'O trader quer crescimento faseado e de longo prazo ate '],
  ['Trader values structured scaling and free monthly resets through subscription renewals.', 'O trader valoriza escalonamento estruturado e reinicios mensais gratuitos atraves das renovacoes da subscricao.'],
  ['"If the trader is newer but wants to grow gradually, send TCP."', '"Se o trader for mais recente mas quiser crescer gradualmente, recomende TCP."'],
  ['RECOMMEND GAUNTLET MINI WHEN', 'RECOMENDAR GAUNTLET MINI QUANDO'],
  ['Trader wants an exam-style challenge with fixed targets.', 'O trader quer um desafio em formato de prova com metas fixas.'],
  ['Trader is comfortable with the subscription + reset model and clear profit / loss metrics.', 'O trader sente-se confortavel com o modelo de subscricao + reinicio e metricas claras de lucro/perda.'],
  ['"If the trader is confident in an existing intraday strategy, send Gauntlet Mini."', '"Se o trader estiver confiante numa estrategia intradiaria existente, recomende Gauntlet Mini."'],

  ['Start sending traders.', 'Comece a enviar traders.'],
  ['Join the program, log in, and grab your assets.', 'Entre no programa, inicie sessao e obtenha os seus materiais.'],
  ['01 \u00b7 Join or log in', '01 \u00b7 Entrar ou iniciar sessao'],
  ['Register a new affiliate account, or sign in if you already have one.', 'Registe uma nova conta de afiliado, ou inicie sessao se ja tiver uma.'],
  ['02 \u00b7 Grab your assets', '02 \u00b7 Obter materiais'],
  ['Affiliate links, banners, and personal discount codes live in the affiliate portal.', 'Links de afiliado, banners e codigos de desconto pessoais estao no portal de afiliados.'],
  ['03 \u00b7 Contact', '03 \u00b7 Contacto'],
  ['Commission / payout, rules clarification, or marketing materials - reach the affiliate team.', 'Comissao / pagamento, esclarecimento de regras, ou materiais de marketing - contacte a equipa de afiliados.'],
  ['Commission / payout, rules clarification, or marketing materials — reach the affiliate team.', 'Comissao / pagamento, esclarecimento de regras, ou materiais de marketing — contacte a equipa de afiliados.'],
  ['Affiliate Program', 'Programa de Afiliados'],
  [' start \u00b7 scales to ', ' inicial \u00b7 escala ate '],
  ['Trader passes a simulated evaluation, then upgrades through LiveSim or ', 'O trader passa uma avaliacao simulada e depois evolui por LiveSim ou '],
  [' with an ', ' com divisao de lucro de '],
  [' profit split. Custom funding offer at the top tier.', ' de lucro. Oferta de financiamento personalizada no nivel mais alto.'],
  ['Passing with rules respected leads to a guaranteed funded offer from ', 'Passar com as regras cumpridas leva a uma oferta financiada garantida da '],
  [', aligned with the evaluation account parameters.', ', alinhada com os parametros da conta de avaliacao.'],
  ['including micros.', 'incluindo micros.'],
  ['children:"Description"', 'children:"Descricao"'],
  ['children:"Outcome"', 'children:"Resultado"'],
  ['children:"Tracking"', 'children:"Rastreio"'],
  ['children:"Definition"', 'children:"Definicao"'],
  ['children:"Violation"', 'children:"Violacao"'],
  ['children:"Commissions"', 'children:"Comissoes"'],
  ['children:"Commission"', 'children:"Comissao"'],
  ['children:"Offers"', 'children:"Ofertas"'],
  ['children:"Subscricao exam"', 'children:"Prova por subscricao"'],
  ['children:"LIVE"', 'children:"REAL"'],
  ['children:"Live"', 'children:"Real"'],
  ['children:"Real brokerage"', 'children:"Corretagem real"'],
  ['children:"Mode"', 'children:"Modo"'],
  ['children:"Data"', 'children:"Dados"'],
  ['children:"Billing"', 'children:"Faturacao"'],
  ['children:"Monthly sub"', 'children:"Subscricao mensal"'],
  ['children:"Withdrawals"', 'children:"Levantamentos"'],
  ['children:"None"', 'children:"Nenhum"'],
  ['children:"Activation"', 'children:"Ativacao"'],
  ['children:"Consistency"', 'children:"Consistencia"'],
  ['children:"Audience"', 'children:"Publico"'],
  ['children:"EXAMPLE"', 'children:"EXEMPLO"'],
  ['children:"End"', 'children:"Fim"'],
  ['18 / 18 · End', '18 / 18 · Fim'],
  [' — do not exceed allowed contracts for your balance.', ' — nao exceder os contratos permitidos para o seu saldo.'],
  [' — never reach or drop below the minimum balance.', ' — nunca atingir nem descer abaixo do saldo minimo.'],
  ['Daily loss limit', 'Limite de perda diaria'],
  [' — hitting it fails the evaluation.', ' — ao atingir, reprova a avaliacao.'],
  ['04 \u00b7 EOD DRAWDOWN \u00b7 HARD', '04 \u00b7 DRAWDOWN EOD \u00b7 GRAVE'],
  [' — hitting the minimum balance is a hard breach.', ' — atingir o saldo minimo e uma violacao grave.'],
  [' — exceeding contract limits blocks the account until next trading day.', ' — exceder os limites de contratos bloqueia a conta ate ao dia seguinte de negociacao.'],
  [' of total profit; if over 30%, the drawdown floor can keep climbing until it reaches starting balance.', ' do lucro total; se passar 30%, o limite de drawdown pode continuar a subir ate atingir o saldo inicial.'],
  ['Transitions to Live after first ', 'Passa para Real apos os primeiros '],
  [' profit (minus ', ' de lucro (menos '],
  ['Pass-through CME data fees (~', 'Taxas CME de dados repercutidas (~'],
  [' / exchange / month)', ' / bolsa / mes)'],
  ['5 days', '5 dias'],
  [' of unscheduled inactivity can terminate the account', ' de inatividade nao programada podem terminar a conta'],
  ['Simulated, withdrawable', 'Simulada, com levantamentos'],
  ['Fixo at ', 'Fixo em '],
  [' on 200K, and ', ' nas contas de 200K e '],
  [' on 400K accounts.', ' nas contas de 400K.'],
  [' open equity can still fail an account even with Drawdown EOD if it dips under the minimum.', ' o capital aberto ainda pode reprovar uma conta mesmo com Drawdown EOD se cair abaixo do minimo.'],
  ['Best day under ', 'Melhor dia abaixo de '],
  [' of total profit target. Stops "one lucky day" passes.', ' da meta de lucro total. Evita aprovacoes por "um dia de sorte".'],
  ['CME, CBOT, NYMEX, COMEX — including micros.', 'CME, CBOT, NYMEX, COMEX — incluindo micros.'],
  ['All pros & nao profissionais', 'Todos os profissionais e nao profissionais'],
  [' / mo', ' / mes'],
  [' — best day under ', ' — melhor dia abaixo de '],
  [' of total profit.', ' do lucro total.'],
  ['Rule break →', 'Quebra de regra →'],
  [' hard risk-rule breaches fail the evaluation. Escada de Progressao overages can lock trading for the day.', ' violacoes graves de risco reprovam a avaliacao. Exceder a Escada de Progressao pode bloquear a negociacao no dia.'],
  ['split)', 'divisao)'],
  ['non-pros', 'nao profissionais'],
  ['non-pros pay no extra data fees. Pros pay per exchange each month.', 'os nao profissionais nao pagam taxas extra de dados. Os profissionais pagam por bolsa todos os meses.'],
  ['Evaluations →', 'Avaliacoes →'],
  ['Pass-through Dados CME fees (~', 'Taxas CME de dados repercutidas (~'],
  ['LiveSim, Live, profit split, activation fee.', 'LiveSim, Real, divisao de lucros, taxa de ativacao.'],
  ['Trader Career Path tiers, outcome, ideal client.', 'Niveis do Trader Career Path, resultado e cliente ideal.'],
  ['Six core rules and what counts as a rule break.', 'Seis regras principais e o que conta como quebra de regra.'],
  ['Profit split, scaling tiers, drawdown by phase, activation.', 'Divisao de lucros, niveis de escalonamento, drawdown por fase e ativacao.'],
  ['Subscricao exam, Helios funding, ideal client.', 'Prova por subscricao, financiamento Helios e cliente ideal.'],
  ['Hard vs soft breaches and copytrading rule.', 'Violacoes graves vs leves e regra de copytrading.'],
  ['Subscricao, resets, risk table by size.', 'Subscricao, reinicios e tabela de risco por tamanho.'],
  ['20% first 2 years, 5% vitalicio, payout terms.', '20% nos primeiros 2 anos, 5% vitalicio e termos de pagamento.'],
  ['Active requirement, tracking, tools, compliance.', 'Requisito de atividade, rastreio, ferramentas e conformidade.'],
  ['Practical guidance with simple trader examples.', 'Orientacao pratica com exemplos simples de traders.'],
  ['Shared rule across TCP and Gauntlet.', 'Regra comum ao TCP e ao Gauntlet.'],
  ['EOD, trailing, fixed — how each behaves.', 'EOD, trailing, fixo — como cada um funciona.'],
  ['Days, hours, hard rules, consistency, profit target.', 'Dias, horarios, regras graves, consistencia e meta de lucro.'],
  ['CME futures allowed, forex and crypto excluded.', 'Futuros CME permitidos, forex e cripto excluidos.'],
  ['Evaluation, LiveSim, Live — billing and data fees.', 'Avaliacao, LiveSim e Real — faturacao e taxas de dados.'],
  ['Join / log in, find assets, who to contact.', 'Aderir / iniciar sessao, obter materiais e saber quem contactar.']
];

const codeReplacements = [
  [
    'function Ch(f){const s=f.match(/^\\/slide(\\d+)$/);if(!s)return-1;const r=parseInt(s[1],10);return Fe.findIndex(c=>c.position===r)}',
    'function Ch(f){const s=(typeof f=="string"?f:"").match(/\\/slide(\\d+)\\/?$/);if(!s)return 0;const r=parseInt(s[1],10),c=Fe.findIndex(o=>o.position===r);return c===-1?0:c}'
  ],
  [
    '",u.jsx("span",{className:"text-accent font-semibold",children:"80/20"})," de lucro. Oferta de financiamento personalizada no nivel mais alto."]',
    '",u.jsx("span",{className:"text-accent font-semibold",children:"80/20"}),". Oferta de financiamento personalizada no nivel mais alto."]'
  ],
  [
    '",u.jsx("span",{className:"text-accent font-semibold",children:"20%"})," divisao)"]',
    '",u.jsx("span",{className:"text-accent font-semibold",children:"20%"})," de divisao)"]'
  ],
  [
    '",u.jsx("span",{className:"text-accent font-semibold",children:"30%"})," fee"]',
    '",u.jsx("span",{className:"text-accent font-semibold",children:"30%"})," taxa"]'
  ],
  [
    '" as comissoes podem ser usadas para comprar contas ou reinicios com um ",u.jsx("span",{className:"text-accent",children:"20%"})," desconto extra sobre as promocoes atuais."',
    '" as comissoes podem ser usadas para comprar contas ou reinicios com um desconto extra de ",u.jsx("span",{className:"text-accent",children:"20%"})," sobre as promocoes atuais."'
  ],
  [
    'children:["The ",u.jsx("span",{className:"font-bold",children:"Escada de Progressao"})," limita os contratos maximos por saldo. Um saldo mais alto permite mais contratos."]',
    'children:["A ",u.jsx("span",{className:"font-bold",children:"Escada de Progressao"})," limita os contratos maximos por saldo. Um saldo mais alto permite mais contratos."]'
  ],
  [
    'children:[u.jsx("span",{className:"font-bold text-text",children:"Limite de perda diaria"})," and ",u.jsx("span",{className:"font-bold text-text",children:"Drawdown EOD"})," — quebrar estas regras reprova a avaliacao."]',
    'children:[u.jsx("span",{className:"font-bold text-text",children:"Limite de perda diaria"})," e ",u.jsx("span",{className:"font-bold text-text",children:"Drawdown EOD"})," — quebrar estas regras reprova a avaliacao."]'
  ],
  [
    '"O trader deve atingir a Meta de lucro para o tamanho da sua conta e cumprir todos os outros objetivos."',
    '"O trader deve atingir a meta de lucro para o tamanho da sua conta e cumprir todos os outros objetivos."'
  ]
];

const cleanupReplacements = [
  ['80/20 de lucro', '80/20'],
  ['20% divisao', '20% de divisao'],
  ['Resets —', 'Reinicios —'],
  [' 30% fee', ' 30% taxa'],
  ['standard', 'padrao'],
  [' com um 20% desconto extra sobre as promocoes atuais.', ' com um desconto extra de 20% sobre as promocoes atuais.'],
  ['The Escada de Progressao', 'A Escada de Progressao'],
  [' caps the max contracts per balance. A higher balance allows more contracts.', ' limita os contratos maximos por saldo. Um saldo mais alto permite mais contratos.'],
  [' — breaking them fails the evaluation.', ' — quebrar estas regras reprova a avaliacao.'],
  [' and Drawdown EOD', ' e Drawdown EOD'],
  ['Trader must reach the ', 'O trader deve atingir a '],
  [' for their account size and meet all other objectives.', ' para o tamanho da sua conta e cumprir todos os outros objetivos.'],
  [' start · scales ate ', ' inicial · escala ate '],
  [' ou Contas reais financiadas com divisao de lucro de ', ' ou contas reais financiadas com divisao de lucro '],
  ['At least ', 'Pelo menos '],
  [' — never reach or drop below. Open and closed equity count.', ' — nunca atingir nem descer abaixo. O capital aberto e fechado conta.'],
  ['Passing with rules respected leads ate a guaranteed funded offer from ', 'Passar com as regras cumpridas leva a uma oferta financiada garantida da '],
  ['Transitions ate Live after first ', 'Passa para Real apos os primeiros '],
  ['Under $300 allowed · ', 'Abaixo de $300 permitido · '],
  ['Self-purchase →', 'Auto-compra →'],
  [' commissions can be used ate buy accounts or resets with a ', ' as comissoes podem ser usadas para comprar contas ou reinicios com um '],
  [' extra discount on top of current promotions.', ' desconto extra sobre as promocoes atuais.'],
  [' renewals do not reset balance.', ' as renovacoes nao reiniciam o saldo.'],
  [' available anytime in evaluation, do not extend subscription, not available once funded.', ' disponiveis a qualquer momento na avaliacao, nao prolongam a subscricao e nao estao disponiveis apos financiamento.'],
  ['// 13 — General rules · Tipos de drawdown', '// 13 — Regras gerais · Tipos de drawdown'],
  ['Important —', 'Importante —'],
  [' nao profissionais pay no extra data fees. Pros pay per exchange each month.', ' os nao profissionais nao pagam taxas extra de dados. Os profissionais pagam por bolsa todos os meses.'],
  ['// 17 — Which offer ate recommend', '// 17 — Que oferta recomendar'],
  ['Trader wants long-term, staged growth up ate ', 'O trader quer crescimento faseado e de longo prazo ate '],
  ['title:"Which offer ate recommend"', 'title:"Que oferta recomendar"'],
  ['description:"Join / log in, find assets, who ate contact."', 'description:"Aderir / iniciar sessao, obter materiais e saber quem contactar."'],
  ['25K start · scales ate 200K', '25K inicial · escala ate 200K'],
  ['50K start · scales ate 400K', '50K inicial · escala ate 400K'],
  ['100K start · scales ate 400K', '100K inicial · escala ate 400K'],
  ['O trader passa uma avaliacao simulada e depois evolui por LiveSim ou Contas reais financiadas com divisao de lucro de 80/20 de lucro. Oferta de financiamento personalizada no nivel mais alto.', 'O trader passa uma avaliacao simulada e depois evolui por LiveSim ou contas reais financiadas com divisao de lucro 80/20. Oferta de financiamento personalizada no nivel mais alto.'],
  ['O trader passa uma avaliacao simulada e depois evolui por LiveSim ou contas reais financiadas com divisao de lucro 80/20 de lucro. Oferta de financiamento personalizada no nivel mais alto.', 'O trader passa uma avaliacao simulada e depois evolui por LiveSim ou contas reais financiadas com divisao de lucro 80/20. Oferta de financiamento personalizada no nivel mais alto.'],
  ['What it takes ate pass.', 'O que e preciso para passar.'],
  ['At least 10 dias de negociacao.', 'Pelo menos 10 dias de negociacao.'],
  ['Limite de perda diaria — never reach or drop below. Open and closed equity count.', 'Limite de perda diaria — nunca atingir nem descer abaixo. O capital aberto e fechado conta.'],
  ['→ up ate 200K', '→ ate 200K'],
  ['→ up ate 400K', '→ ate 400K'],
  ['Progression: hitting profit target and withdrawing triggers auto-upgrade ate the next tier.', 'Progressao: atingir a meta de lucro e levantar fundos ativa a subida automatica para o nivel seguinte.'],
  ['Passing with rules respected leads ate a guaranteed funded offer from Helios Trading Partners, alinhada com os parametros da conta de avaliacao.', 'Passar com as regras cumpridas leva a uma oferta financiada garantida da Helios Trading Partners, alinhada com os parametros da conta de avaliacao.'],
  ['04 · DRAWDOWN EOD · HARD', '04 · DRAWDOWN EOD · GRAVE'],
  ['Subscricao — renewals do not reset balance.', 'Subscricao — as renovacoes nao reiniciam o saldo.'],
  ['Resets — available anytime in evaluation, do not extend subscription, not available once funded.', 'Reinicios — disponiveis a qualquer momento na avaliacao, nao prolongam a subscricao e nao estao disponiveis apos financiamento.'],
  ['The path from pass ate live capital.', 'O percurso da aprovacao ao capital real.'],
  ['Transitions ate Live after first $5K de lucro (menos 20% divisao)', 'Passa para Real apos os primeiros $5K de lucro (menos 20% de divisao)'],
  ['Passa para Real apos os primeiros $5K de lucro (menos 20% divisao)', 'Passa para Real apos os primeiros $5K de lucro (menos 20% de divisao)'],
  ['$300 standard', '$300 padrao'],
  ['Under $300 allowed · 30% fee', 'Abaixo de $300 permitido · 30% taxa'],
  ['Abaixo de $300 permitido · 30% fee', 'Abaixo de $300 permitido · 30% taxa'],
  ['Self-purchase → commissions can be used ate buy accounts or resets with a 20% extra discount on top of current promotions.', 'Auto-compra → as comissoes podem ser usadas para comprar contas ou reinicios com um desconto extra de 20% sobre as promocoes atuais.'],
  ['Auto-compra → as comissoes podem ser usadas para comprar contas ou reinicios com um 20% desconto extra sobre as promocoes atuais.', 'Auto-compra → as comissoes podem ser usadas para comprar contas ou reinicios com um desconto extra de 20% sobre as promocoes atuais.'],
  ['Maintain active status under the current affiliate terms ate keep your payout tier. Confirm current requirements in the affiliate portal before promoting.', 'Mantenha o estado ativo segundo os termos atuais de afiliado para manter o seu nivel de pagamento. Confirme os requisitos atuais no portal de afiliados antes de promover.'],
  ['The Escada de Progressao caps the max contracts per balance. A higher balance allows more contracts.', 'A Escada de Progressao limita os contratos maximos por saldo. Um saldo mais alto permite mais contratos.'],
  ['The Escada de Progressao caps the max contracts per balance. Um saldo mais alto permite mais contratos.', 'A Escada de Progressao limita os contratos maximos por saldo. Um saldo mais alto permite mais contratos.'],
  ['// 13 — GENERAL RULES · TIPOS DE DRAWDOWN', '// 13 — REGRAS GERAIS · TIPOS DE DRAWDOWN'],
  ['Fixo drawdown', 'Drawdown fixo'],
  ['IMPORTANT — o capital aberto ainda pode reprovar uma conta mesmo com Drawdown EOD se cair abaixo do minimo.', 'IMPORTANTE — o capital aberto ainda pode reprovar uma conta mesmo com Drawdown EOD se cair abaixo do minimo.'],
  ['Limite de perda diaria and Drawdown EOD — breaking them fails the evaluation.', 'Limite de perda diaria e Drawdown EOD — quebrar estas regras reprova a avaliacao.'],
  ['Limite de perda diaria and Drawdown EOD — quebrar estas regras reprova a avaliacao.', 'Limite de perda diaria e Drawdown EOD — quebrar estas regras reprova a avaliacao.'],
  ['Trader must reach the Meta de lucro for their account size and meet all other objectives.', 'O trader deve atingir a meta de lucro para o tamanho da sua conta e cumprir todos os outros objetivos.'],
  ['Trader must reach the Meta de lucro for their account size and cumprir todos os outros objetivos.', 'O trader deve atingir a meta de lucro para o tamanho da sua conta e cumprir todos os outros objetivos.'],
  ['Simulada, withdrawable', 'Simulada, com levantamentos'],
  ['Avaliacoes → nao profissionais pay no extra data fees. Pros pay per exchange each month.', 'Avaliacoes → os nao profissionais nao pagam taxas extra de dados. Os profissionais pagam por bolsa todos os meses.'],
  ['// 17 — WHICH OFFER ATE RECOMMEND', '// 17 — QUE OFERTA RECOMENDAR'],
  ['Match the trader ate the offer.', 'Associe o trader a oferta certa.'],
  ['Trader wants long-term, staged growth up ate 200K / 400K.', 'O trader quer crescimento faseado e de longo prazo ate 200K / 400K.'],
  ['"If the trader is newer but wants ate grow gradually, send TCP."', '"Se o trader for mais recente mas quiser crescer gradualmente, recomende TCP."'],
  ['Resets — disponiveis a qualquer momento na avaliacao, nao prolongam a subscricao e nao estao disponiveis apos financiamento.', 'Reinicios — disponiveis a qualquer momento na avaliacao, nao prolongam a subscricao e nao estao disponiveis apos financiamento.']
];

for (const [from, to] of replacements) {
  content = content.split(from).join(to);
}

for (const [from, to] of cleanupReplacements) {
  content = content.split(from).join(to);
}

for (const [from, to] of codeReplacements) {
  content = content.split(from).join(to);
}

fs.writeFileSync(targetPath, content, 'utf8');
console.log('OK');